### ISSUE TITLE
Please keep only required dependencies

### ISSUE THREAD

**Issue by vitalk** [mdulchevskiy/leverx_courses#14]
https://github.com/mdulchevskiy/leverx_courses/blob/5d63cc9e29d45ccd9d7e3326fd8658392198bb61/Task%204/requirements.txt#L7

**Comment by mdulchevskiy** [comment]
SQLAlchemy used to create a connection to the database. You can find it in 55 line of code:
`self.__engine = sqlalchemy.create_engine(f'mysql+pymysql://{user}:{password}@{server}')`
